name: todo_riverpod
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  flutter_riverpod: ^2.6.1
  logger: ^2.6.1
  firebase_messaging: ^16.0.4
  firebase_storage: ^13.0.4
  cloud_firestore: ^6.1.0
  firebase_core: ^4.2.1
  flutter_lints: ^6.0.0
  intl: ^0.20.2
  firebase_analytics: ^12.0.4
  flutter_signin_button: ^2.1.1
  flutter_svg: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: ^0.8.1 

flutter:
  uses-material-design: true

  assets:
    - assets/